### ISSUE TITLE
flutter web problem about refresh page

### ISSUE THREAD

**Issue by devchenli** [kauemurakami/getx_pattern#13]
getx_pattern_example Project

from ListPage to DetailPage, 
And click browser's  refresh button ,
Then crashed :
```
data != null
"A non-null String must be provided to a Text widget."
```

<img width="712" alt="截屏2021-01-04 20 09 45" src="https://user-images.githubusercontent.com/46481943/103533868-d8a43d00-4ec8-11eb-9956-39b6ec5f29f4.png">

So,When User refreshed current page, the data will be lost.

**Comment by kauemurakami** [comment]
Hello devchenli, you heard some updates, I will pass on today, thanks for your feedback, I will leave this issue open to give you feedback.
Going forward, the GetX widget does not currently allow us to have heavy children, that is, lists, grids, or large chains of components (container does not count as a widget in this case).
So I would start replacing it with an **Obx ()**, passing this function, which gives it in our list of posts, to the onInit of our GetxController and consuming the controller provided by Binding with our **GetView <DetailsController>**

**Comment by keremcankabadayi** [comment]
https://github.com/flutter/flutter/issues/59277

**Comment by ali-1989** [comment]
can use [Restoration](https://docs.google.com/document/d/1KIiq5CdqnSXxQXbZIDy2Ukc-JHFyLak1JR8e2cm3eO4/edit#)
