### ISSUE TITLE
Global controllers

### ISSUE THREAD

**Issue by Drolegc** [kauemurakami/getx_pattern#15]
Hi! 
There's a place for global controllers?
For example, I need the user to be global, for that, I use a UserController with the user in it.
Should I make a folder called global_controllers?

**Comment by pradyotMobifyi** [comment]
Yeah need to know the structure for global controllers or for initial bindings.
Should we add it in the `app/data/service` or need to follow any other file structure.

**Comment by kauemurakami** [comment]
Thinking about these forms, yes, it would be a type of service auth (a session), so that you load this user throughout the application, and GetxService is exactly for that. So yes, here at github you already have this data / services / user_service.dart structure

**Comment by paanoop** [comment]
@Drolegc use `GetXSerive` it is just awesome. Like a controller, but global and stays till app is on. In the documentation it says `app/service` for such things. Wonder why @kauemurakami is suggesting to keep it in `data / services / user_service.dart`
