### ISSUE TITLE
Dúvida: onde ficariam as interfaces que são implementadas pelos `services`, `repositories` e `providers`?

### ISSUE THREAD

**Issue by aismaniotto** [kauemurakami/getx_pattern#28]
Olá, nessa estrutura existe um lugar apropriado para colocar as interfaces que serão implementadas? Como por exemplo `IProductApi`, para que na injeção de dependências, durante os testes, a classe  `IProductApiMock` seja chamada. 
Ou essas classes ficaram juntas às suas implementações?
Teria algum lugar apropriado para colocar as classes mockadas também? Talvez dentro ou fora de `Data`?

E uma classe de service, digamos CameraService, que abstrai o uso da camera do dispositivo, também ficaria dentro de `Data`?
E classes de validação, cujo único objetivo é receber um valor e retornar os erros, ficariam dentro de utils?

Curti bastante o projeto, parabéns!
Grato desde já.

**Comment by kauemurakami** [comment]
Olá @aismaniotto, é bem simples, inicialmente vou te dar um exemplo que eu mesmo utilizo com a camera.
Em várias partes do meu app uso pages como, NPS( aquelas notas que você da ao terminar alguma ação) e câmera, que por sua vez, apenas vai tirar fotos e enviar para uma determinada função ( callback, recebida como parametro, ou argumento).
Crio módulos para eles, ou somente pages, isso você deve decidir dependendo do módulo.
A camera por exemplo, necessito de um modulo mais robusto, por ter que usar diversas funções no controller, passando funçoes como parâmetros para ele, para que ele possa se adaptar a diferentes chamadas, apenas alterando seu callback, então o mesmo **modulo** com esse onInit você pode dar um find<Service> nele.
No caso do NPS, crio apenas uma page, pois é uma função mais simples, e sempre sabemos que o AuthService estará na memória pra recuperação rápida de dos do usuário, entao podemos apenas setar seu texto, de maneira componentizada, e seu callback, usando diretamento o Get.find<Service>.
Os dois jeitos são validos, você pode ter um módulo que implementa um service, ou usar um service existente para acrescentar e "globalizar" esse controller, de forma que toda intereção tenha um ponto final ou pare com o service armazenando os dados necessarios.
Obrigado, e peço desculpas pela demora.

**Comment by kauemurakami** [comment]
Uma coisa que me esqueci é, todo service que tenha interação com a API, deve ter um repository, o mesmo vale para o controller, portanto se em seu controllador do módulo camera, onde também esta page e binding, você consumir um service que enviará sua foto pra api, deve-se deixar essa função no service, consumindo o repository do mesmo, caso use apenas dessa forma, seu módulo nem irá precisar de um repository.
Mas as views, são restritas aos módulos e widgets globais.
Sobre as implements, não, mas você me deu algo pra pensar.
Você utiliza essas interfaces apenas em testes? os testes vão ser inseridos em algum tempo aqui na estrutura, e penso em deixar cada módulo com seus tester internos, ou seja, existiria um folder camera_test no seu modulo camera, nele irá conter o arquivo de teste, seu mock e sua interface, mas pra isso temos que nos atentar ao rodar os testes e setar os locais certos, mas mesmo assim ide's e editores de texto como vscode possuem ferramentas auxiliares que facilitam a execução dos testes.
Mas como ainda não validei, recomendo testar por módulo, criando uma pasta para cada módulo em test, dessa forma você terá a mesma estrutura de módules em seus testes, podendo usar diretamente Get.put(Controller()) para trazer seu controller e começar a testar ou diretamente as funções do repository com seus dados mockados, que seria apenas uma instância simples do repository.

**Comment by aismaniotto** [comment]
Então, sobre a produção de testes não tenho muitas dúvidas não. 
A intenção de utilizar as interfaces é para a injeção e inversão de dependência, utilizei os testes como exemplo.

Voltando para o exemplo da Camera, teoricamente, eu não preciso de uma page, a ideia seria gerar:
```
abstract class CameraService {
  Future<Photo> openCamera();
}

class CameraServiceImpl implements CameraService {
  @override
  Future<Photo> openCamera() async {
    // some logic that use from a third party package, open a camera and return the photo

    return SomePackage.Photo();
  }
}

class CameraServiceMock implements CameraService {
  @override
  Future<Photo> openCamera() async {

    // fake data that not use the package, because in tests it's not necessary test à third party package
    return Photo();
  }
}

``` 

No exemplo, seriam essas três classes. Hoje, numa arquitetura mais comum, eu colocaria numa pasta `service` todos os serviços de "terceiros", como por exemplo o acesso à câmera e que não teria necessariamente relação com a camada de dados. Nessa estrutura do getx_pattern, à classe de acesso à câmera (que não possui uma page ou controller) também ficaria junto com os demais serviços na camada de dados?

**Comment by kauemurakami** [comment]
Exatamente, um service aqui pode ser lido como algum serviço necessario na aplicação, de forma que esse serviço esteja disponivel sempre que necessario, independente do local, no seu caso a camera service, você pode usar um service ativo em todo app para controllar o estado dele, e usar um widget global, assim vira um módulo generico, que servira a outros modulos como complemento.
No seu caso, eu usario uma classe abstrata, por ser poucos métodos e não necessariamente você vai implementar os mesmos métodos em todas as views, caso siga com a implement use em `utils` por ser um utilitario da camera, nao relacionado a nenhum provedor ou módulo.
