### ISSUE TITLE
getcontroller importando package desnecessário.

### ISSUE THREAD

**Issue by guihsdev** [kauemurakami/getx_pattern#3]
O comando `getcontroller` está importando o package `import 'package:meta/meta.dart';`.

Ao fazer este _import_ o VS Code já identifica o mesmo como não utilizado.

Print da classe gerada.
![image](https://user-images.githubusercontent.com/39705535/89206578-dcd1d480-d58f-11ea-8c3d-7e931f914b40.png)

**Comment by kauemurakami** [comment]
Snippet corrigido, valeu pelo toque Gui !
