### ISSUE TITLE
why folder views is double?

### ISSUE THREAD

**Issue by adibpwd** [kauemurakami/getx_pattern#30]
![DeepinScreenshot_select-area_20210925083537](https://user-images.githubusercontent.com/54851209/134753522-c0cab95d-fda5-4779-9b9e-ac2553af2fc5.png)

**Comment by kauemurakami** [comment]
in this package structure, this example may be wrong, I think it means something like:
Views/Android
          /Ios.....

**Comment by adibpwd** [comment]
solved with command : get create view:clock on app
