### ISSUE TITLE
Site Translations

### ISSUE THREAD

**Issue by electraport** [kauemurakami/getx_pattern#39]
Hi, I am a US-based developer who is getting to know Flutter and has adopted the GetX pattern. I wanted to see if you were interested in some help translating the page on https://kauemurakami.github.io/getx_pattern/ where there is room for improvement. Translating it will help me learn the pattern even better so I am glad to work on it, but I don't see it in a repo where I can make the changes and send a PR. Is there somewhere I can offer edits?

Thanks!

**Comment by kauemurakami** [comment]
Hello @ElectraPort , of course we are open to contributions.

You can fork it, create a branch and submit it for merge into develop, which I will recreate at this moment, I saw it was closed.

Any questions my contact is on my profile, you can call me in person.

Thanks for the contact and interest.

**Comment by mrashidcit** [comment]
Hi ElectraPort,
   I have done some improvements in the App Translation in then "getx_pattern_site".
This is my first Comment & Pull Request on GitHub.  So I'm just mentioning the link of the Repo : https://github.com/mrashidcit/getx_pattern

For further details you can check the repo.

And **kauemurakami** If I'm violating anything here the let me know.

**Comment by electraport** [comment]
Thank you! Had gotten distracted playing with a drag-and-drop editor but this is important and we are definitely strong Get users so I will take another look at this tonight.

**Comment by kauemurakami** [comment]
Everything ok, anything I'm here.
I accepted your pull request and I'm working on a new approach that will be released this week, I'll let you know through this issue :)
Thanks for contributing.
