### ISSUE TITLE
What is the purpose of android folder in ui?

### ISSUE THREAD

**Issue by stefandevo** [kauemurakami/getx_pattern#4]
Hi, thx for the getx_pattern and the getx snippets.
Looking through your site and sample, I saw the ui/android and ui/ios folders.
Any reason to split this up. Is this if you want different ui for each platform?
What if you want 1 ui, regardless of platform.
Would you then just put everything directly under the ui/ folder, or use something like ui/shared ?

**Comment by kauemurakami** [comment]
Hello Stefan, well, when developing the pattern according to some needs, I thought as follows.
Usually you develop the Android app with material, and many things are reused.
So I thought in a way that the person could develop his application for android, and change some specific widgets such as snackbars, or dialogs for example, even some screens.
But really, your question is very valid, I didn't think about it this way:
If all my pages were **unique** for each platform.
I'll think about it.
But answering your question if I came across this problem, which is what is happening lol, a screen for each platform.
In the structure of packages I would create a **shared** within **ui**, and in it I would place the pages that will be responsible for determining the use of the **respective page** for a given platform.
But I think that depending on the project, I would make the whole android application customizing widgets that give a very strong visual difference when used on iOS.
As all this is only important at the time of compilation, you can reuse a lot of android code and according to the platform you are going to build using the correct widgets, or pages.
Tell me if you can get around the situation in a simple way, if you can't think together in a pleasant way.
