### ISSUE TITLE
Erros de escrita no site

### ISSUE THREAD

**Issue by ambitencourt** [kauemurakami/getx_pattern#9]
Prezados, de antemão gostaria de parabenizar ao trabalho de todos vocês que desenvolvem o Getx e afins. Não sei onde exatamente reportar os errinhos de escrita, então resolvi criar uma issue e enviei uma mensagem no Facebook do Kauê. Segue um PDF dos trechos que precisa corrigir. Não corrigi os jargões e o uso "doméstico" de palavras inglesas, tornando aportuguesadas. Já que sou iniciante na programação, não consigo contribuir no código, mas na escrita do Português não sou iniciante, hehe. 
[getx_pattern correção.pdf](https://github.com/kauemurakami/getx_pattern/files/5485458/getx_pattern.correcao.pdf)

**Comment by ambitencourt** [comment]
Será editado diretamente, agradeço o retorno.

**Comment by kauemurakami** [comment]
obrigado, você conseguiu fazer a PR ?
